### PR TITLE
Add audit logs

### PR DESCRIPTION
**Pull request by QuantumEnigmaa**
Towards https://github.com/giantswarm/giantswarm/issues/28346

This PR adds lines in the promtail config so that it can retrieve audit logs. Currently testing on a v19.1.0 cluster

### CODE REVIEW

**Review by QuentinBisson — APPROVED** [review]
LGTM, do you think we can deploy it only on control-plane nodes?

**Comment by hervenicol** [comment]
> deploy it only on control-plane nodes?

Quite unlikely.
Promtail is a daemonset, all pods use the same config.

Maybe you have an idea how we should have a specific config for some nodes?

**Comment by QuentinBisson** [comment]
@hervenicol I would think we could use the node role label for this but as long as it's not erroring out I'm fine

**Comment by QuentinBisson** [comment]
@QuantumEnigmaa maybe it's because it's too long? Have you tried using a `|` ?

**Comment by QuentinBisson** [comment]
See https://stackoverflow.com/a/21699210

**Comment by QuantumEnigmaa** [comment]
Fixed and working on `gauss` : 
image

**Review by QuentinBisson — APPROVED** [review]

**Review by hervenicol — APPROVED** [review]

**Pull request merged**
